name: Altın Bildirim

on:
  schedule:
    - cron: '0 6 * * *'  # UTC 06:00 = Istanbul 09:00
  workflow_dispatch:       # Manuel test için

jobs:
  bildirim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install requests
      - run: python altin_bildirim_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.8704029287:AAE7r2D3N-E1a8Oiis3SmYa0_e6k3HyoMqE }}
          CHAT_ID: ${{ secrets.5700720643 }}
